title: Open Design Kit
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - params.json
  - Dockerfile
  - 'docker-*.yml'
  - '*.sh'
collections:
    methods:
        output: true
        permalink: /methods/:path/
permalink: title
gems:
    - jekyll-minifier
